version: '3.4'

services:
  crimeapi:
    image: ${DOCKER_REGISTRY-}crimeapi
    build:
      context: .
      dockerfile: CrimeApi/Dockerfile
    depends_on:
    - mongodbservice
    - lawenforcementapi
    ports:
      - 80:80
  
  lawenforcementapi:
    image: ${DOCKER_REGISTRY-}lawenforcementapi
    build:
      context: .
      dockerfile: LawEnforcementApi/Dockerfile
    ports:
      - 80:80

  mongodbservice:
    image: mongo
    restart: always

  mssqlservice:
    image: mcr.microsoft.com/mssql/server:2019-CU5-ubuntu-16.04
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SA_PASSWORD=AbcDef10
      - MSSQL_DB=LawEnforcementDb
    ports:
      - 1433:1433
