version: '3.4'

services:
  crimeapi:
    image: ${DOCKER_REGISTRY-}crimeapi
    build:
      context: .
      dockerfile: CrimeApi/Dockerfile
    depends_on:
    - mongodbservice
    - lawenforcementapi
    - rabbitmq
  
  lawenforcementapi:
    image: ${DOCKER_REGISTRY-}lawenforcementapi
    build:
      context: .
      dockerfile: LawEnforcementApi/Dockerfile

  mongodbservice:
    image: mongo
    restart: always

  repcrimegateway:
    image: ${DOCKER_REGISTRY-}repcrimegateway
    build:
      context: .
      dockerfile: RepCrimeGateway/Dockerfile
    depends_on:
    - crimeapi
    - lawenforcementapi
    ports:
      - 80:80

  crimefeedbackservice:
    image: ${DOCKER_REGISTRY-}crimefeedbackservice
    build:
      context: .
      dockerfile: CrimeFeedbackService/Dockerfile
    depends_on:
    - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 15672:15672
      - 5672:5672