version: '3.4'

services:
  crimeapi:
    image: ${DOCKER_REGISTRY-}crimeapi
    build:
      context: .
      dockerfile: CrimeApi/Dockerfile
    depends_on:
    - mongodbservice
    - lawenforcementapi
    ports:
      - 80
  
  lawenforcementapi:
    image: ${DOCKER_REGISTRY-}lawenforcementapi
    build:
      context: .
      dockerfile: LawEnforcementApi/Dockerfile
    ports:
      - 80

  mongodbservice:
    image: mongo
    restart: always

  repcrimegateway:
    image: ${DOCKER_REGISTRY-}repcrimegateway
    build:
      context: .
      dockerfile: RepCrimeGateway/Dockerfile
    depends_on:
    - crimeapi
    - lawenforcementapi
    ports:
      - 80