kubectl apply -f k8sNamespace.yml
kubectl apply -f "https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml"
kubectl apply -f k8sRabbitMq.yml
kubectl apply -f k8sMongoConfigMap.yml
kubectl apply -f k8sMongoSecret.yml
kubectl apply -f k8sMongo.yml
kubectl apply -f k8sCrimeApi.yml
kubectl apply -f k8sLawEnforcementApi.yml
kubectl apply -f k8sRepCrimeGateway.yml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/cloud/deploy.yaml
kubectl apply -f k8sIngress.yml